# Generated by Django 3.1.1 on 2020-09-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
        ('curriculum', '0005_auto_20200927_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
