# Generated by Django 3.1.1 on 2020-09-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_auto_20200929_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='comm_name',
        ),
    ]
