# Generated by Django 3.1.1 on 2020-09-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_auto_20200929_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lesson_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='curriculum.lesson'),
        ),
    ]
