# Generated by Django 3.1.1 on 2020-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_auto_20200929_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comm_name',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
