# Generated by Django 3.1.1 on 2020-10-03 07:44

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_auto_20201001_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, upload_to=curriculum.models.save_subject_image, verbose_name='Subject Image'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
