# Generated by Django 3.1.1 on 2020-10-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_auto_20201003_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
