# Generated by Django 3.1.1 on 2020-10-03 12:26

import curriculum.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_subject_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(default='0000', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Notes',
            field=models.FileField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Chapter no.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ppt',
            field=models.FileField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Presentations'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Video'),
        ),
    ]
