# Generated by Django 2.2.10 on 2021-05-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0028_auto_20210511_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotsubject',
            name='slot_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_slots_subject', to='curriculum.Subject'),
        ),
    ]
